In [1]:
import numpy as np

In [2]:
def Rx (phi):
    t = phi * np.pi / 180
    c = np.cos (t)
    s = np.sin (t)
    return np.array ([
        [1, 0,  0, 0],
        [0, c, -s, 0],
        [0, s,  c, 0],
        [0, 0,  0, 1]
    ])

In [3]:
Rx (30)

array([[ 1.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.8660254, -0.5      ,  0.       ],
       [ 0.       ,  0.5      ,  0.8660254,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [4]:
def Tz (z):
    return np.array ([
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, z],
        [0, 0, 0, 1]
    ])

In [5]:
Tz (10)

array([[ 1,  0,  0,  0],
       [ 0,  1,  0,  0],
       [ 0,  0,  1, 10],
       [ 0,  0,  0,  1]])

In [6]:
Rx (30) @ Tz (10)

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.8660254 , -0.5       , -5.        ],
       [ 0.        ,  0.5       ,  0.8660254 ,  8.66025404],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])